#!/bin/bash
############################################################
#
# upload-haddocks
# Copyright (C) 2017, Richard Cook
# Released under MIT License
# https://github.com/rcook/hidden-char
#
############################################################

set -euo pipefail
IFS=$'\n\t'

script_dir=$(cd $(dirname $0); pwd -P)
repo_dir=$(dirname $script_dir)

cd $repo_dir
$script_dir/bootstrap -m upload_haddocks $*
